status = warn
name = OpenLineageTerminalConfig

appenders = console
appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss} %-5p %c - %m%n

rootLogger.level = warn
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = CONSOLE

loggers = consoleTransport
logger.consoleTransport.name = io.openlineage.client.transports.ConsoleTransport
logger.consoleTransport.level = info
logger.consoleTransport.additivity = false
logger.consoleTransport.appenderRefs = console
logger.consoleTransport.appenderRef.console.ref = CONSOLE
